### ISSUE TITLE
Problems when killing chronos buffer while timer runs

### ISSUE THREAD

**Issue by Silex** [dxknight/chronos#1]
Hello,

Killing the `*chronos*` buffer while a timer runs creates all sorts of trouble.

There are several solutions to this problem, but I suggest that:
- update the buffer only if it exists
- add some interactive function to display it again

**Comment by dxknight** [comment]
Well, don't kill the `*chronos*` buffer then :smile:

Seriously, good catch and thanks for letting me know.  I have removed `chronos-kill` and its default binding to `Q`, updated `chronos--update-display` to only update if the buffer is live, and have added a couple of functions into the kill-buffer process to handle killing the `*chronos*` buffer properly.  

Restarting is handled by `chronos-add-timer` which sets up the `*chronos*` buffer if necessary.

The updated documentation now reads:
- Quitting, Killing and restarting
  
  Quitting with `q` buries the `*chronos*` buffer, but timers continue to run. Switch back to the `*chronos*` buffer when required.
  
  Killing the `*chronos*` buffer in the usual way (typically `C-x k`) deletes any timers (after user confirmation) and closes the buffer. To restart after a kill, use `M-x chronos-add-timer`.

**Comment by Silex** [comment]
Thanks :+1:
